version: "2.0"
services:
  "tws":
    image: ib-tws
    build: .
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - tws:/home/tws:rw
      - /tmp/.X11-unix/:/tmp/.X11-unix/:ro
      - ~/.Xauthority:/home/tws/.Xauthority:rw

volumes:
  tws:
